let input = System.IO.File.ReadAllText "d3.txt"
let i2 = "vJrwpWtwJgWrhcsFMMfFFhFp
jqHRNqRjqzjGDLGLrsFMfFZSrLrFZsSL
PmmdzqPrVvPwwTWBwg
wMqvLMZHhHMvwLHjbvcjnnSBnvTQFn
ttgJtRGJQctTZtZT
CrZsJsPPZsGzwwsLwLmpwMDw"

let i3 = "vJrrdQlGBQWPTBTF
fcpTMnMqMfTnZpgMfPbFBWzHPpBPzbCPPH
mcVMfcsqZgmgVcmfgcmZmqZNJhrlrdhNhDdrRRJSvDTRhJlD
pMFRmLwHMbRPmMbPPddvqqrrNSTFVttdrN
hgfpgCGZcjpcgfvNtdrtjvrdtSrd
gZgsBBBlZggBGhsfhpzlzLDLmLRDRMLDPw
hChhMFCvqtTMwbSSHgTZWHZd
jjBNPjJJNfsNjVnVJJNcNfPwGbSbDZnZZgHrddwHrrgWGb
mBBRRmBBQBmNJWhCzqllzhRCCv
lQgpngNgQvHdSgWwjMRmDjmMDHmm
zCLVzfzzbbCzsZZPbZPLfFJJMDWWRcDsmJRcjmwTmlRj
BblftzBtlFznptSQQQppNG
wJJwqCtCGRcVlqlM
BQpppjBQLczTrvHRjH
QQQFnmQWWRfnpQBpQpfDCwCdbPDCwbNNPtdJPCZw
gpJjshBpgjZGppJqBGJjJZzTwzTmcvzwwcmvwsCFdmcF
WPSSWWSQLVdDDfWltDWLPfttvFCVmzCCTFnmwcnnnCTCzVVv
tLldLltDQfflrRWNqBRjgHBpJNZjHj
bzVJjVnjbCGVLZQLmmsJZZQQ
RrwwzhPScWSwrhvZZvZlZvvSTsQS
HwFhzFWdPHfcPwPWPdhWffnngpjtnjgtpnfGCGnG
CPwQtftDQfPDBPBCfDDDCDptszcpVVddcRczVLVdccRGrLWs
FqlSnhlqhmhMbHqqSQlHbcrRrsWzRdzdWVzLRGRrVF
MbQmSnHZhqZMQMTJCttjCgPCwfgDwT
CCSpvHtZHSwftFtdtbfR
QJmNPmjjJNgNVNSzDlmRqbWlqWWfcqfWqbwfqR
MDhJzmSMDmsZrLhssrvh
ZhznnrLzcHhHSjsjSBSsBnSS
dTwqDdqDRQjNdwqjldggDvBJfmBfTSBbBSvfSJsmff
DjCldNglVwFVgZHHHzhCMcLhMC
vBnShjwwSshmQPmtJLpJtn
rDLFCWrClWCMWWVrbFVJqpQqpHmtbzJPQzJmzb
ZMCCDCMNrTWTrgScgGRhsvcsGLSG
LQpJglQQRjQsppfsQbjfbQlBgBhFhrvghhZCdPZZZthPgv
zVHDMSWVVMVWDzmnVMHDSMMzZvNFFrFvPCdmdFdNdrBPZhhd
ncqqSzMVCcGWVSCTWCDcVTffLLLbJsLLsRLblRQTps
zjGzLQtFzzRgwwLhVrqw
dfClCdHZsmffZDWlBZHCDBmhJbqTgbwgqbTnwrgrqRbT
HsdwPCsWDpDsBpfdWdHldWpsGvvccPvGcvzQvFQvccjNztQt
wmVVgFPrFdwJrlNHQHSHCCHL
tWBtvnBqZZMpcvmmqMBRCQQLCLWCHfNQQCSGWL
BBsnmcpqPswFsTws
BQRpFPJJJJPmPRqZNFVhcczHHzggwjBhghgzHw
snTsTLtrlvSSSslsGdcwmjhgggvjHhmH
nSsWWTtCbbDSnlRRZCfFRNZmCVJf
tRRMCWLtJWQLqLrmLHVLqmqh
JszPjSbGbsnGnSZprVpFhvFqvhrqZZ
zgbGSDBbPsTgbDBzzSDnDnPTcWlWJCQlNttNwwwMcMctcW
hlVRvPvzqqtRdwRRJsst
HHVNVBMBjHLTjVjwDjsbjJwbdmbbss
NBZHMCNVCCpgLTWggBpgNLTvqCPnGhQhCCGlqlhfcvvGfn
mwbfbfbDCqRJZRbCSvmfWTQFczTznnnFTFnrzJsz
BdhHlLjpjjjncSprnsSFWS
ljhVBPjSdHPRfZRZDvVRZM
tGqbqBSsntRgNqwNNVVHVN
hclFvJZvCDFppDpZpHNggMTwdlrMQNVgHM
CCFmcZLDFpvzZhCFJvZvmwjSRWsBLWsnfWjRRGGfnsst
GdGQQFdcMPwMdLFvWsNWFDLfss
SqjhtjnrbVznSztSqtzpjztVvTmNNmmfMMfDDMDDNTqfgsqv
rVhhZjppVrhpVzRbjSnzHPMwlJCJQdcRPPlPPcHJ
JVQLVgVZghFtFlhghtvSzsddmrdvssmzSWtd
HTMJCBMCjnwNBnCbTNwMdWfzvzsrsvffWbdsmfPr
BGnnpDnTjjHJwDBNpqlFQVQFQclcRFQqpR
BRhbrQDttbTTtRDtTRRzLHWZLZHGSqWLCBNWqLNL
fwFPPSjmsmJGLsNH
dvfSdvfVMjPTttTzczgTcd
dZgggwzgvsggtdstZTZgdfnhSJSSJDDhnDBdppnGnhSp
VQWRQWVCRLFGnThJCpFJ
LbmmbQVcHcmmlWjmVlVQNVRzvwwZvTrsrNwNwzZrMvfsqt
lDZQSlHDbLccRPQhCNhG
gtsntgvdvBvvqgsTgBggdrWRNzPhWczPbWcdWCccGGGP
sTBttvrFnnMTMJngbqfLlZLpwFVljwppZZDl
zNNNgqpgmLgqlHBHsMGslH
WdWFrFwhcwWRwhddcRWcdQbcDDslzBDszsHbGBDfbHfzVlVl
ZvhRrvPQwvWFQRZvFdJttSPgCmNppCNzJnJS
fCzRRNGfqNRvwpQhwrGcwZZT
gJnStgMmLhdHndSSTjcTrTpcmrjjcrrw
FFJBbdddFPPhFFNWCF
btrHRSBBSNLLRPLwhbhpqpfWhQppWZ
zCzTvvmgDvgDZhqWZZthtDZh
ttTjMsvCgRRLRSsBRG
LsSFFTTDWdCsmFTlLSsLDDRRQCvhpRQGNGQBJBhGGMNB
zqPtqZnjPPrPvJHBMHrJrMpv
VbqfjZfwgtfjPgZPgtwDLTLcTlcFdWLdcdVTJF
pfMCDmpHbdMQQdQFFG
gdjldRsVFRntQnqR
rlJVsWgWPWjsslSpDbScmSDPHfCd
lnFFGgBFBslDFGbFSjnNTjjppSrQHhnT
zcvmCRcvZmcZzWpTQhQrrTSPtHWH
CRccrZJmdJlwDJwgswGg
hllrrDzggGppgSSLNWgW
jlTlPwwqjjntVpWWPNnP
wjjJqvQjJjQJbTjlFqhBMzfDDmMCGBMHDCGb
jvQPhhtCRtfmqHHjqHHJsl
FFSTcBTBTMwFGCTwMTcGwTVnsHSJzqqJJJplmlpJHszZZzZD
dLMdVMNGBdGFMTNTRRLrQWCQhgWQbhgf
gdRgdgzzrvrzggDwgDGpPLzrbNljMTsbWWjWjZbTjLZMWcWj
tFfCQHJJnJMJTJjNNMjl
HmtffVttqHQmBCBQCqfFnCwRqpDvPRrGppRggNzdwgzp
DHSqzQbzWlRLDzMZNpVLgnpNLggw
cZcdTmPPthPdsvvdhPGTvJgwnpgjjTgNNwMVngNBjNfn
PPdJPvrtGtcFdFFchDRHDqHzZWSQQCrQWQ
BcgnLBLsFvRnGRRRlzfJbbPJzwHPwPFz
hCDjWMDVNfVllfzddw
qqMqpWCMjDTWNWTBLpgsgLvZwtGLLg
zczPgpGzhnbmbchhHwqwhSwfwHCFWw
VJdmVLlLdVJSJWHSTFwH
rlttQLVLdvvZpgcGbmDrzGMD
WSvtpqqtqccttVQpVvJNJSVNCmTlnCWwTTnWlBBBjwCBTlTP
ZgfPHfPfMHsDCwnlGBwTMGBM
rgdffZhPrrLsdLZpvcFSJJNvpJhcJv
qVdqJGvzgJzJgwzgWvdJzpblcRRWmLFFcLBmllFRRMRFRH
TGGSsSssNPTSLlRLcPHMmnPB
tTjTZtNGhrCjQNCjQQDTCSjZvfJbdgqrdpwqfVzwgzvdvVgb
VTmwcTVSMHwbMwbDVBTcMpJfpfnWqdJbZpJldfsjZn
hNtPhtzFzPQGCCGFFCGtnqQqWZWplsjWdlnlldJn
vRCRzvvFFFvhrRthPtLrtNGSwBVDScDSgHHjwwcBgSgTSL
dWCsWbWWchblsmbWVZqqsSpsGfBqBVBB
DtTtjPJrgjjtTTwgPwwjrTgnLqSBZQLqngQppqnfBVQfGp
PJPwwtDwHGGJtJRFHmhCFRCvdmHR
mMsMJSCjllsSSmBBclsMsJHDbcHqqbHpqHGbDZHbqHpb
RnQnGVnzGzFQgzWzpzvpqDHW
QVhRTfGLLFGTTFFwhnQVNfFwJsJsMjsBMrlsjrJlPSPlTrls
JNMJSVSGVCjnWZMZWWcH
gLTcqbqhqbbgzgnjpnjjWHnP
wqlbcrfTwrvcLBwwRtJwsNRstRsCCN
MlBssQBchZDLNJZgmvGg
fdzHMfHSzSprfgSvvJbmvDGNDW
PCHTRfjHnzHMzzfrCPCpMTlFhcFstqVwVCFllQcBtqss
TtFnnFJfDhtdfJJcFtfnsfcFjBjLDjHrDLrCjMjwCLLrZjrS
qQmWmQzvWpRQGvgpGGRGRzmWwZMwBLCHMZjbBBCLwrHSLrqr
MRllgRWWMlsJFnlFclJT
SRRrRDRBRTdbdMRZBZMprTCJCnWGvChJGzLSWWzsGhCs
wwqHPtFwjwTHLHvGTsGW
FlPtqTNVcTVtwtmjRbBZfQbfZbQmRRMR
WSWfQttffsHSfRRRStfnCsQQqlJpbhnrnmNzJbzqNbbrpmnb
FGFPddBcBwDPzpzbWlpzDbbh
ZPdPPLMFdGwFFGdwGdZwcZgTtSTVCsRRSgSRTQWTTtCTtH
vHsfGHTvSvHHHsGHctMgtHrJwbJJwrjgbrdzjWCrdrrw
hqZRLmmZpFhcLhFmrzJQbzzmQQJWJJbm
LNZFcpPlhBRhqDDllRtnMssGfBsnttGTnttT
VDVrLrZZcjrhhFrZppGlglGMPFwFWNQw
bzszSBHBWNGcscpN
TJqBqSfTBBqBHzJqddBqzcLnLjnhCRTvvRrnDrvrvZRn
GLzrNWbtMptHDmNDglgmlD
fZtcfCRvtBcQjdjgmmjj
RhBhhqfSPPpttrnPnVVW
BhVRJGwWqtHjZqTDLZ
gQnfpBdPNpQrPNSfBdndnpTTDFZttDLLzZzTzCLNLZZD
mQQPsgrldpgdBQgSbGVcmcRwGMWhwVwW
DrLCctBCLQtSSQcLbcQHWvvvlWHHnWlWBlNRRB
wqdmpgqsZhzGphwwpZGsppRvfnJsWfHWvfFfWFsfvlNN
mwmhVppTqpGqpNZpqTbSLLttDrDDtPQTtr
qwqmgnglDnlgtQzQJzJQhmWQ
pTpTpssdsVvNsdTSZGdSdjvCRcqcRcVWVczhWChtchzWcR
sGTvPqZvSGdZZGdsvNGdPHrFHFBDlDLwPgBFLLBB
BBBGsGGBrBBrqWVqRnWBBBWpzFwMhjMFSFPzzSwPFPpzzFvg
HtCdDdDctZDtbHCffcbddbNfvjvFSPFjMhMgLwPgjbFhjFFj
NJTDdltNgCNDZJJZCDJZDfJtrWWnQGBqlRVVlrBsnlrqqmnr
PwZhgbZSWSqqGznv
tTPVVmptcsrNrsTNpjRzqfHvvGfGWjfjqGzHWn
RVRtVDRmsRtrctmJDtgBBhBhbFgJPFFMFJgP
jPzzCCPzTtTfzrRtgSNVRHvFQVvbpQppVN
sSnDlBGBwJbFNplVlN
cLwSwdMhSwcBcsBZgWjCTCWfCLffrg
RSNPvTTNqFTSvNrSBvBGJGzmFMslgCMJCgmzlc
fDVfpptLWQfnVLffVHbQDQCclJzGGCtGmmGJmzMshzGh
VfQnWZfZDbdnVHWcfWnfHWVvPrTSNZqSwSqPjjvBwRqrNS
FLRpmRwcpjfzjSnD
tGvPNvBnPQggPQQvPgNHDjSSjDzzthjzfHrjlT
JGqvWNCCGQBWGBQvVLsCMMRLRnRMnwMc
fGJbzgBffCGpPGDVnG
mcTccshvbbdRNRsNjdLjnVlHVnHLqVpDpDqD
wdmsWvWssbZTcWvRhfzMQtrzMgrfrZJgfQ
NfSbvZHZNRSbQbbQgZrMjhLwMrjLjwHLCmmh
NTWdJBFcWJFcdsFJqcqPwqmjpMrLCMpLMwLP
dNJctnFBVfSGgvnfZz
GSnRJfGfRJgMDMGWnfzdmptpFJppLvwLwvLt
hbjZzrQbblqcLtpwlHvFplTH
qrzqbschrQCqqjPcCVcCGDfGMWDgWNGDDSfgnf
vmMpCdTndCvMdmnFcCRJWBJGcZJRJB
NDNwGzshPLrwVVNsjswhGzjFSfFFQQRSJWRBFcFRfsWFQB
NwNhNjVzhhzzrgzdqqvqtnqvlqdggG
MdPLVSSlMMVMmlLBBLFdvZNWqWztStttRRNqzqNGTq
DhJfhghhCgwChJgJwHHzbsHpnZRtTWqqfZRGTnWTZtNqNRWR
hwHpJbprwpQhDHDCbCCzsClBvrLMVFPvmPlMMVMdLrvj
DssDrqRsWsNfzfsWLRzjgTdBlgzFpMlgTFTglT
ttCZnSQmSQmgjGQGQgDlBp
bhDnCmbwVmCwwtZttPwbRWsRJcqWJfcfsfrqVrqq
ldBgTMTRvBDVnCCCTdSRTqNjbjSbPPPPqtfPqtPJFJ
cZHZrszLrrrZHrbNjNtbJCfqNJLt
GZzCzWZGGsGzmzZcmGssZzZVvnVdBDddRRDnVlWgRTDdBM
RjNrrjwGDDqqGJsHtzpMHHGz
QCbWgbShmBCCPClmmWFHzJzTbDdsMJsTtpTD
fffQfnSCWDBfhCDLRrNrwcrqVqwNqn
zmRrDRzqjmLLHzDjLsHLflJlVVJlWWTDTfdMtlWJ
pPQQnbvSpvNbgfgfVtMVJfgdtG
SnpnVFcPnNnPvpNSFNSbhHLhrjhCqRsRBRrHCLhzmC
CZZzlnCZNlGGcbVrbtVlMtct
MgFQDFgQRLLHhJgDFqQJQLgdtVTrttSrPSmcbmTtvSqvVSTV
hFQDDfMDfLgHwWfBzWwwsZGW
bHVDdHVHTPMvnSQnWSDQgDmm
GhrCJfbfrhfbRJcqGqlwZtnBRtBWSQgQWWnWQW
lfcCrqJhlfFqphpplNCrNVMPMPLbsLPLzFVHVLsVdz
VDhFCZhtFdPqwwcp
SvnvHNNnTvbwNNgnHwTHgwBTLcdqmmfmqLGmmTRLPfpdGP
BNWsHJgSnwgMMgMBBWMDVJjtjZrDJZzztJhjQr
HDsSHLRnpjbpbbRDbqLjLjjGGVffMVGMdvnfMcNvfBBGcB
TCzQQztwwNTMqMdBVv
hCQWmtCzZthPPZPrLjSbJqjSjLLFjLpr
ZrrZqJDcZSCFLLHBFcjjHF
TgvnDTlTtQwgBfwwwzLjGLdF
VbnVngMtvDTTVMQDQMDQlsbZJChCmCPhprrZqhqZSZPJ
glMGHBJTJJTplgwcCgcqcFhhbWncFm
sSswtPfRDmWcCqfchq
RZSdSzsVzNPSwSSQsdzSSQpGLjJTMpBGrJrLLrplZBpG
WQqqwLqQlnlWDwtbVbtCNfVbpV
dFTRjBPhcBgBrFhTPhrbVptJpNNbbtJCbJSL
hjcmcRmgPPcRcPDmHHzGLWmsDmzH
rWFmrRmmccSZJWvSLZTH
hDPhGbhSjtbpqJLvJHjLHTqj
pnplBlfBPPhlgfDbDhglPMMrwrRRSSncwccQzddzmC
LbccJCGzbcCJcfGczcnmNnvNmZNLSDZZWPWS
dwstRhTsrsFddPZqvNWP
BBggRrQstBwBRTHWTprRCHHGVljfCGCfcljHjbGV
FHVBSVDvnsFDwwSVwwvGVSMFWhWcWptMWchWMtPPcWtNNWcj
TgqJrJTRmRCNrbcLjprLnp
qQTlfdlZQgmfqqnFVznvQwvnsBsV
TGpDDMQGMZNtfvDJdtWd
jbrmstmllRmNvVhmmvJVhv
tbrRzFFLlRrjFlLlTQgLQwwLMwgTZBTB
QFgFWQQfSgLFGmtnnVmqCPWmPH
TTzjgTbRRqnRsCPCsP
NDMMgZjzcJvbjhMcjZbbbJJNpdpBfBvSBBQwBSQLQSpSplBG
zcRNsQSSMjRsNNZZFBLQHHFFBPWF
tvwCtgvqLJNnNBCH
fNNwqrqNMpTrDlcs
MMHMVPRJHJWvqzWctbtQQdQz
DFfNFffDnTllfTfFfmzsjqcdtQGQpbddQQbssn
mlFNCgFNNNLrmLFCThhhzJBvhSJPVhMgMh
PWjhljbHFhjbFMWhjbPfhbTGZvlGcGlCLvvwtGCNZGvc
SRqBqBrmQWQrgQrrqrJBLZNccLNZmTCtvTGtCvCt
rJDzDSSBrzdqQWDPHFMjMFdjHMVnbM
qqLwvvtrLFqqfqrjjjdBZfBCBBJdlT
ZGZpRZHbQDzDWRRRVdBzSSlBdzjjzdJJ
ZGpgNDQmWGDRmRpZMQbvPPtnnFnLsstFmnFrPL
TdhcfZhdZZdpdbPWttCWrrCN
MBMMqRLgpGpFFWbNsvLwvCPCCP
mpBMnBRMBGqJfZcfZZHZlhfm
CdmGdnMcMwHjhDtFFnrj
vPbVbPBPPpgpgWJpvTjqDZZqSHqVZShrDj
BppjjgvbJjbpNbzPfNcGCLlCRcmLLflllGcc
qDtgVttGFtlslStS
gCZbbHCjvJbZjCbJhHhHJrZcslJcLzLllcLNFssMSsTlSM
CWbWrZgWBQQBBpfdPm
hstPtCGtltlTClllPJLScVdPdJjLPJMV
NHRbDZDQSDFFjjdJ
RqbQpgBmqZvqZNQqgZmmbszpTtthtCswhjslwwpTWC
CVdwBJJdppbbwdBVrJbrJbGPlMFSLrjrPjmPFFmPRRDF
NNWHHhNZTcQWhnNFlmSSlRmLjnPPRF
qWsccHTZccsNsZcvTcNtStpBtbdVwpfBwbVCBq
lPQHNJhMPMPFlNMHBqZBwQwQwQZwcCqw
bWddDzbWbftdDSDbgttgnSDWccLwcvBczqcqGZzLccZTZwwc
spWrssWrnDtDpfSWDtsFqlFPjNMjRJVVNNPJNp
bCCfcWVLTHfSSdHwhH
sGQSZSzQJmmQsphwHHHsndnpHN
zPSqrmZPFCvFTbWMLV
tLtVBGLJqGqVGbzGSCsSsSqQsFvZCSQv
gRgdWlHTBHgjjHlWpWjWjrwdCfQRZFSssQQQZmQmMSvZfFMQ
lPHlpWgjTldprNWHNNdHjTctcLbVcnNJJGbVzBhnbhhJ
zVrSwzzJbVrbqFCVVVwVCztWDDtfTZsWDZTLZZmSWsDm
bpgHlgBbbGGGglBGRNvMpWfTDjmDfWDjfRZZWLtmZs
bGbvQHMpQccFJPPh
VGqCPmPjfGqCdMqVMhjhmPChDJDJzvrrbrBvrdrpnJDpJDQr
TSRsgHRSFHTlHvJvBDvvzlptbv
ZFLTsRRgZTgWscHTfWNWNPPBfGqmmMfV
TvTrrrCVCVwqjPrWfWhjfH
RRmgmnggltRgNpzRsdfqWWjdFdvNHfdh
zZlRzDGGZmbmmZbvGJVccwCMVcVVTLwDwC
QPsNlvvvSccbbNQcSPvDVSvzTLLCgRVzCJgTJpgCpphgzh
MDqHwFrMffgFpgpJLzTz
ZtdrffBrdqmBBmfwMtDtQPPPbjcNvnllnlbNtScn
HbbbcpTHHMMqNTCddCVBQvgPzJPJWQBQjvpBvQ
FFrDGtntFFwhrRFDFthfRhRmSJPJvvJZjZjWJJvJQJnvWjjg
rtfFfLmLRmNgdHqcLNHd
FpFHCFWtFSnCWnBfJJfgMJDGHDGGsG
rhrLrrhLrbtZThLfgsfGNDfgTgNcDs
QmPjbdqjmbbbrmhQqQZrZStRdlnnFdlRzVVVWlnpzR
bBMwwjzhbjhssvsGZBSZLr
JFtnDtRzJtffJHWNtHncRRrvGZvSnllZZZsgvlnvVvlv
RRPHPHFPHHdcHtzNfMQhdCwbqCmbMChhqq
pWGdFSWwwjLdvgNNvggl
mTNbmRPHmmVNmvZhnhBssBlhnb
HPTzRPffJJNzjCFpDWDz
MHlgzsqHlbmzgsHzlsbcRWPdPtjZFqhGGdrPrjPJGrVP
vpwwvQwCnhNQpSnLdVtrrZGZtZjdVSdJ
hfffwvTpvLwDpCLvDnQDHbmRRTcWRHMWWHWMmWMW
WHlNHWWldjpwntnWBPpPQFZFBFhZBZCZ
TqqvgvmgfmvDVLLfqqLsrFBRhrrBFJQBGPgPZGCR
mcDbcDmzLcmDDzfVzTQNjNzNztdzjNdwSHlH"



//for each line, split on the middle
//find the one character that is in both lists (set?)
//convert to char -> byte -> subtract some value

//find the common character in a single line
let findCommon (s: string) =
  let s1 = set (s.Substring (0 , (String.length s)/2))
  let s2 = set (s.Substring ((String.length s)/2))
  Set.minElement(Set.intersect s1 s2)

//convert characters to their values
let char2num (c: char) =
  let i = int c
  if i >= 96 then
    i - 96
  else
    i - 38

let score (i: string) =
  List.ofArray (i.Split "\n")
  |> List.map (fun x -> (char2num (findCommon x)))
  |> List.sum

let findCommon2 s1 s2 s3 =
  let S1 = set s1
  let S2 = set s2
  let S3 = set s3
  Set.minElement (Set.intersect (Set.intersect S1 S2) S3)

let score2 (i: string) =
  let rec help ss =
    match ss with
    | s1::s2::s3::ss' -> (findCommon2 s1 s2 s3)::help ss'
    | _ -> []

  help (List.ofArray (i.Split "\n"))
  |> List.map char2num
  |> List.sum